INSERT INTO USERS(USERNAME,PASSWORD,ENABLED) values('user','pass','Y');

INSERT INTO USERS(USERNAME,PASSWORD,ENABLED) values('admin','admin123','Y');

INSERT INTO AUTHORITIES(USERNAME,AUTHORITY) values('user','ROLE_USER');

INSERT INTO AUTHORITIES(USERNAME,AUTHORITY) values('admin','ROLE_ADMIN');
